### ISSUE TITLE
Request to Make Wiktionary Parser Publicly Accessible

### ISSUE THREAD

**Issue by HaydenCampbell** [doozan/spanish_data#2]
Hello,

I'm interested in creating a dictionary with a unique format using the wordlist entries. However, I've encountered an issue with the link to your [Wiktionary Parser](https://github.com/doozan/enwiktionary_parser), which appears to be broken.

Is there a possibility of making the parser publicly accessible?

Thank you and kind regards,
Hayden

**Comment by doozan** [comment]
The correct link is https://github.com/doozan/wtparser
